# Generated by /apollo/env/SDETools/perl/lib/perl5.8/Amazon/BrazilTools/WorkspaceManager.pm
#-*- makefile -*-
# 
# Note: This file should be kept as lean as possible. Please only 
# use this file for bootstrapping the local copy of BrazilTools.

# path to the Brazil package cache
BRAZIL_LIBRARY_BASE := /opt/brazil-pkg-cache

MAKE_INFO_DIRECTORY = $(BRAZIL_HOME)/make-support

ifeq ($(shell if [ -x /apollo/env/SDETools/bin/brazil-bootstrap ]; then echo YES; fi),YES)
    # IMPORTANT: We unset PERL5LIB because older versions of build-release-parallel
    # Passed on PERL5LIB path that points to the local BrazilTools that has already
    # Been bootstrapped.
    ifeq ($(BRAZIL_BUILD_TOOLS),)
        BRAZILTOOLS_MAKE_BASE:=$(shell PERL5LIB= $(BRAZIL_TIMER) /apollo/env/SDETools/bin/brazil-bootstrap -package BrazilTools-2.1)
    else
        # BRAZIL_BUILD_TOOLS is set by brazil-build which sets-up
        SPACE:= $(NULL) # Space
        _root:=$(strip $(foreach root,$(subst :,$(SPACE),  \
            $(BRAZIL_BUILD_TOOLS)),                        \
            $(if $(findstring /env/BrazilTools-2.1/,$(root)),$(root))))
       ifeq ($(_root),)
           $(shell echo "*********************************************************" 1>&2)
           $(shell echo "Expected BrazilTools-2.1 to be in BRAZIL_BUILD_TOOLS, got" 1>&2)
           $(shell echo "$(BRAZIL_BUILD_TOOLS)" 1>&2)
           $(shell echo "See http://w?ExpectedBrazilTools-2.1" 1>&2)
           $(shell echo "*********************************************************" 1>&2)
           $(error Searching BRAZIL_BUILD_TOOLS failed)
       else
           BRAZILTOOLS_MAKE_BASE:=$(_root)
       endif
    endif

    ifeq ($(BRAZILTOOLS_MAKE_BASE),)
        $(error brazil-bootstrap failed)
    endif

    BRAZIL_BOOTSTRAP_VERSION := $(if $(findstring build,$(notdir $(BRAZILTOOLS_MAKE_BASE))),0,1)
    export BRAZILTOOLS_MAKE_BASE
    BRAZILTOOLS_SRC_BASE:=$(BRAZILTOOLS_MAKE_BASE)
else
    include $(MAKE_INFO_DIRECTORY)/BrazilTools-2.1.mk 

    # the following (incredibly obvious) make logic toggles the BRAZILTOOLS_SRC_BASE
    # to deal with whether BrazilTools is in the package cache (tacking on src) or
    # in a local path (leaving it alone)
    BRAZILTOOLS_IN_CACHE=$(findstring $(BRAZIL_LIBRARY_BASE),$(BRAZILTOOLS_MAKE_BASE))

    # DIR_OVERHAUL_TODO - the following logic can be simplified once all version
    # sets are caching packages in the new format
    BRAZIL_LIBRARY_BASE_NEW := $(BRAZIL_LIBRARY_BASE)/packages
    BRAZIL_LIBRARY_BASE_OLD := $(BRAZIL_LIBRARY_BASE)/lib
    BRAZILTOOLS_IN_OLD_CACHE=$(findstring $(BRAZIL_LIBRARY_BASE_OLD),$(BRAZILTOOLS_MAKE_BASE))
    BRAZILTOOLS_CACHE_BASE := $(if $(BRAZILTOOLS_IN_OLD_CACHE),$(BRAZILTOOLS_MAKE_BASE)/src,$(BRAZILTOOLS_MAKE_BASE)/generic-flavor/src)

    BRAZILTOOLS_SRC_BASE:=$(if $(BRAZILTOOLS_IN_CACHE),$(BRAZILTOOLS_CACHE_BASE),$(BRAZILTOOLS_MAKE_BASE))
endif

BRAZIL_MAKEFILES_DIRECTORY=$(BRAZILTOOLS_SRC_BASE)/makefiles

##############################################################
# Transfer control to BrazilTools
##############################################################
include $(BRAZIL_MAKEFILES_DIRECTORY)/brazil.mk

