# Generated by /apollo/env/SDETools/perl/lib/perl5.8/Amazon/BrazilTools/WorkspaceManager.pm
# -*- makefile -*-
# $Id: //brazil/src/appgroup/brazil/apps/BrazilLibraryTypes/mainline/perlModules/lib/Amazon/BrazilTools/WorkspaceManager.pm#3 $
# this file is parsed by things other than make, so keep it simple.
# don't reference any variables or anything else evil like that.
#	sed -n 's/^BRAZILTOOLS_MAKE_BASE.*=//p'
# must do the right thing.
#
# update...someone didn't follow the above rule when introducing
# $(shell).  since it didn't break anything, the above comment is
# presumably bogus now.
#
# However, please remember to use := when using $(shell) unless the
# variable is rarely evaluated (less than once per make execution,
# which isn't true for anything in this file).  If you don't, the
# shell command is run every time the variable is executed, which
# can easily be hundreds of times per make command, which is very
# bad for performance.  So don't do that.
#
# BrazilTools make base is automatically extracted from the current
# version set of your build client
# DIR_OVERHAUL_TODO - The "1" argument tells the script to cache BT in the new
# directory structure. This can be removed/deprecated if/when the /opt/amazon
# script always caches in the new dir structure, which should probably be done
# in early 2006
GLOBAL_TOOLS_BIN?=/opt/amazon/platform-services/etc/BrazilTools-2.1/bin/DEV.STD.PTHREAD

ifndef BRAZILTOOLS_MAKE_BASE 
  BRAZILTOOLS_MAKE_BASE:=$(shell $(GLOBAL_TOOLS_BIN)/get-BrazilTools-make-base $(BRAZIL_HOME) 1)
endif

export BRAZILTOOLS_MAKE_BASE

